#! /bin/bash

# Create the DEVSHELL_PROJECT_ID on a VM
curl "http://metadata.google.internal/computeMetadata/v1/project/project-id" -H "Metadata-Flavor: Google" > Project
_ID
awk '{print "export DEVSHELL_PROJECT_ID=" $0, "\n" "export BUCKET=" $0, "\n" "export JAVA_HOME=/usr/lib/jvm/java-8-
openjdk-amd64/jre" }' Project_ID > env.txt
source env.txt
rm env.txt

BUCKET=$DEVSHELL_PROJECT_ID
PROJECT_ID=$BUCKET
DEVSHELL_PROJECT_ID=$BUCKET

MYREGION=us-central1
echo "http://ip4.me/"
MYZONE=us-central1-a
BROWSER_IP=139.47.85.80

#APIKEY=AIzaSyALHf20PB71HxtrbkJyeNzHuTQlgOnNKfU


alias l='ls -lrtpa'
echo "BUCKET        [$BUCKET]"
echo "PROJECT_ID    [$PROJECT_ID]"
echo "MYREGION      [$MYREGION]"
echo "MYZONE        [$MYZONE]"
echo "BROWSER_IP    [$BROWSER_IP]"
echo "APIKEY               [$APIKEY]"
echo "DEVSHELL_PROJECT_ID               [$DEVSHELL_PROJECT_ID]"

export DEVSHELL_PROJECT_ID 
export BUCKET 
export APIKEY
export PS1="$BUCKET> "

mysqlInstance="qwiklabs-demo"
alias sqlcli='gcloud sql connect $mysqlInstance --user=root'
